name = "hask-softwares-website" # Ensure this matches your Cloudflare Pages project name
compatibility_date = "2025-06-26" # Update to a recent date
pages_build_output_dir = "build"

# Optional: For local development with wrangler pages dev
# [dev]
# port = 3000 # Example port
# command = "npm run start" # If you have a specific dev command that serves both
